p8105_hw1_jer2243
================
Juliet Rowe
2023-09-18

# Problem 1

## Load libraries and dataset

``` r
library("moderndive")
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.2     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.2     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.1     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
data("early_january_weather")
```

## Data description

``` r
?early_january_weather

nrow(early_january_weather)
```

    ## [1] 358

``` r
ncol(early_january_weather)
```

    ## [1] 15

``` r
mean_temp <- mean(pull(early_january_weather, temp))
print(mean_temp)
```

    ## [1] 39.58212

The “early_january_weather” dataset contains 358 rows representing
hourly measurements and 15 variables. Variables include “origin”,
“year,month,day,hour”, “temp”, “dewp”, “humid”, “wind_dir”,
“wind_speed”, “wind_gust”, “precip”, “pressure”, “visib”, and
“time_hour”. The mean temperature equals 39.58212 degrees Fahrenheit.

## Scatterplot creation and export

``` r
library(ggplot2)
gg <- ggplot(data=early_january_weather, aes(x=time_hour, y=temp, color=humid)) + geom_point()

ggsave("scatterplot_temp_vs_time.png", plot=gg, width=10, height=7)
```

Overall, temperatures rose throughout the month of January. Throughout
each day, the plot generally shows temperatures dropping during the
night and rising during the day. Humidity levels seemed to peak around
January 11-14.

# Problem 2

## Variable creation

``` r
  random <- rnorm(10, sd=1)
  logical <-  random > 0
  character <- c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J")
  factor <- factor(rep(c("A", "B", "C"), length.out=10))
```

## Create dataframe

``` r
hw1_df=tibble(
  random,
  logical,
  character,
  factor
)
```

## Taking the mean of each variable

``` r
mean_random <- mean(pull(hw1_df, random))
mean_logical <- mean(pull(hw1_df, logical))
mean_character <- mean(pull(hw1_df, character))
```

    ## Warning in mean.default(pull(hw1_df, character)): argument is not numeric or
    ## logical: returning NA

``` r
mean_factor <- mean(pull(hw1_df, factor))
```

    ## Warning in mean.default(pull(hw1_df, factor)): argument is not numeric or
    ## logical: returning NA

Mean of the random variable = -0.0623 Mean of the logical variable = 0.4
Mean of the character and factor variables cannot be calculated.

## Applying the as.numeric function to the logical, character, and factor variables.

``` r
as.numeric(logical)
as.numeric(character)
as.numeric(factor)
```

Applying this function to the logical variable codes “FALSE” as 0 and
“TRUE” as 1. This explains how the mean of the logical variable came out
to be 0.6. Applying this function to the character variable just causes
all of the values to be missing, or “NA”, explaining why taking the mean
results in an error, as the characters cannot be converted to a number.
Finally, the factor variable takes on the value of its level - in this
case, 1, 2, or 3, since we coded it to have 3 levels.
